# Lektion 6 - Introduktion till deep learning-ramverk

**Assignment: Tensors and a tiny neural network**

Instructions:
1. Choose PyTorch or Keras
2. Keep the model small and run quickly
3. Explain what each block does

## Task 1: Tensor operations
Create and manipulate tensors to understand shapes and broadcasting.

In [ ]:
# TODO: Create a tensor with shape (2, 3)
import torch

tensor = torch.randn(2, 3)
print("Tensor shape:", tensor.shape)
print(tensor)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/andreas/ML-Frameworks/ML-Frameworks/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/andreas/ML-Frameworks/ML-Frameworks/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/andreas/ML-Frameworks/ML-Frameworks/.venv/lib/python3.11/site-packages/ipykernel/

Tensor shape: torch.Size([2, 3])
tensor([[-1.1870, -1.4078, -0.7145],
        [ 2.5714,  1.2101, -0.8099]])


In [2]:
# TODO: Reshape to (3, 2)
reshaped_tensor = tensor.reshape(3, 2)
print("Reshaped tensor shape:", reshaped_tensor.shape)
print(reshaped_tensor)

Reshaped tensor shape: torch.Size([3, 2])
tensor([[-1.1870, -1.4078],
        [-0.7145,  2.5714],
        [ 1.2101, -0.8099]])


In [ ]:
# TODO: Demonstrate broadcasting with another tensor
other_tensor = torch.ones(2)  # Shape (2,)
print("Other tensor:", other_tensor)
broadcasted_sum = reshaped_tensor + other_tensor  # Broadcasts other_tensor to shape (3, 2)
print("Broadcasted sum shape:", broadcasted_sum.shape)
print(broadcasted_sum)

Other tensor: tensor([1., 1.])
Broadcasted sum shape: torch.Size([3, 2])
tensor([[-0.1870, -0.4078],
        [ 0.2855,  3.5714],
        [ 2.2101,  0.1901]])


## Task 2: Build a tiny neural network
Keep the model small and runnable.

In [6]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using device: {device}")

Using device: mps


In [7]:
# TODO: Use MNIST or iris (flattened)
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])
train_data = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_data = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [ ]:
# TODO: Build a model with:
# - 1 hidden layer (ReLU)
# - output layer (softmax or sigmoid)

In [ ]:
# TODO: Train for a few epochs and print accuracy

## Task 3: Compare APIs
Reflect on the differences between PyTorch and Keras.

In [ ]:
# TODO: Write 4-6 comment lines on:
# - where PyTorch feels lower level
# - where Keras feels higher level

In [ ]:
print("Done! You built and trained a simple neural network.")