# Lektion 14 - Framtida trender och etik

**Assignment: JAX jit + basic fairness checks**

Instructions:
1. Run a tiny JAX demo (or skip if unavailable)
2. Do a simple bias check with code
3. Write short reflections in comments

## Task 1: JAX jit demo
Try JAX jit on a small function and compare runtimes.

In [ ]:
# TODO: Create a simple function in JAX (e.g., matrix multiply)

import jax
import jax.numpy as jnp

# Vi definerar en funktion matMul som utför en matrismultiplikation
def matMul(a,b):
    return a @ b


a = jnp.ones((200,200))

c = jnp.ones((1,1))
y = matMul(a, 4*a)
print(y)





[[800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 ...
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]]


In [ ]:
# Vi definerar en till funktion, som beskriver
# en rät linje (räta linjens ekvation)

def linear(x):
    k = 3
    m = 1
    y = k*x + m
    return y


print ("Värdet av vår funktion f(x) = kx + m, där k är 3, och m är 1 är:", linear(3))

f_linear = jax.jit(linear)

print ("Enligt Jax är värdet av vår funktion f(x) = kx + m, där k är 3, och m är 1 är:", f_linear(3))

# Vi kan låta jax räkna ut derivata av vår funktion (mycket användbart)
df_linear = jax.grad(linear)

# Vår deriverade funktion förväntar sig en float, eftersom derivata är odefinerat
# för integers. (integers har inga grannar)
print("Derivatan av vår funktion är:", df_linear(3.0))

Värdet av vår funktion f(x) = kx + m, där k är 3, och m är 1 är: 10
Enligt Jax är värdet av vår funktion f(x) = kx + m, där k är 3, och m är 1 är: 10
Derivatan av vår funktion är: 3.0


In [3]:
a

Array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [41]:
# TODO: Run once without jit and once with jit
import time

# I den här cellen har vi två matriser
# a: 200 x 200 ettor
# b : 200 x 200 sjuor
a = jnp.ones((200,200))
b = 7 * jnp.ones((200,200))

# Vi gör matrismultiplikationen (från vår funktion)
# på de två matriserna. Vi för den dels rå,
# och dels med JAX/jit
start = time.perf_counter()
_ = matMul(a, b).block_until_ready()
t_nojit = time.perf_counter() - start

matmul_jit = jax.jit(matMul)
start = time.perf_counter()
_ = matmul_jit(a, b).block_until_ready()
t_jit = time.perf_counter() - start

print(f"JAX no-jit: {t_nojit:.4f}s, jit: {t_jit:.4f}s")

JAX no-jit: 0.0006s, jit: 0.0003s


In [ ]:
# TODO: Compare runtime and add 2-3 comment lines

# Under första körningen var Jit segare än utan. 
# I alla efterföljande körningar var den blixtsnabb.
# Detta är förväntat beteende, då JAX först
# Mappar ut logiken för nätverket, och sedan kör! 
# I längden är JAX mycket mycket snabbare

## Task 2: Bias check (toy example)
Build a small dataset and compare group metrics.

In [ ]:
# TODO: Create a small synthetic dataset with a "group" column

In [ ]:
# TODO: Train a simple classifier (sklearn is fine)

In [ ]:
# TODO: Compute accuracy per group and compare

## Task 3: Reflection
Write short reflections on bias risks and mitigation.

In [ ]:
# TODO: Write 4-6 comment lines about:
# - risks of bias in data
# - one mitigation you can implement in code

In [ ]:
print("Done! You explored trends and responsible ML in code.")